#!/bin/bash
# AutoDNS Sync Service
# Generated by AutoDNS Dashboard
# This script calls the artisan command to sync all tracked domains

ARTISAN_PATH="/path/to/your/project/artisan"
PHP_BIN=$(which php)

cd "$(dirname "$ARTISAN_PATH")" || exit 1

$PHP_BIN artisan dns:auto-sync >> storage/logs/dns-sync.log 2>&1
