#!/bin/bash
# Auto DNS Domain Sync Service
# Generated by Auto DNS Domain

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PHP_BIN=$(which php 2>/dev/null || /usr/bin/php 2>/dev/null || /usr/local/bin/php 2>/dev/null || echo "")

if [ -z "$PHP_BIN" ]; then
    echo "[ERROR] PHP binary not found" >> "$SCRIPT_DIR/storage/logs/dns-sync.log"
    exit 1
fi

cd "$SCRIPT_DIR" || exit 1
$PHP_BIN artisan dns:auto-sync >> "$SCRIPT_DIR/storage/logs/dns-sync.log" 2>&1
